# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "run test"
  lane :test do
    scan(
      device: "iPhone 14"
    )
  end

  lane :build_sym do
    xcodebuild(
      project: "uitest-sample.xcodeproj",
      scheme: "uitest-sample",
      configuration: "Debug",
      destination: 'platform=iOS Simulator,name=iPhone 8,OS=latest',
      derivedDataPath: 'build_output'
      )
  end
end
