name: maestro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache bundle directory
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run test
      run: |
        bundle exec fastlane build_sym
        xcrun simctl install Booted build_output/Build/Products/Debug-iphonesimulator/uitest-sample.app
    - name: setup maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
    - name: run maestro
      run: |
        maestro test ios_sample_flow.yaml