name: CI

on: [push]

jobs:
  build:

    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ '11', '11.3.1' ]
        os: [ macos-10.15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run test with ${{ matrix.xcode }}
      run: DEVELOPER_DIR='/Applications/Xcode_${{{ matrix.xcode }}.app/Contents/Developer' bundle exec fastlane test
