name: XCUITest

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        xcode: [ '11.4.1', '11.5', 'latest' ]
        os: [ macOS-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: set Xcode Version ${{ matrix.xcode }}
      run: |
        if [ "${{ matrix.xcode }}" = 'latest' ]; then
          export XCODE_BETA_APP=`ls /Applications/ | grep Xcode_ | awk 'match($0, /.*beta.*/) {print substr($0, RSTART, RLENGTH-9)}' | sort -n | tail -1`

          if [ "${XCODE_BETA_APP}" = "" ]; then
            export XCODE_APP=`ls /Applications/ | grep Xcode_ | awk '$0 ~ /.*\.app/' | sort -n | tail -1`
          else
            export XCODE_APP="${XCODE_BETA_APP}_beta.app"
          fi
        else
          export XCODE_APP="Xcode_${{ matrix.xcode }}.app"
        fi
        echo "set: ${XCODE_APP}"
        echo "::set-env name=XCODE_VERSION::${XCODE_APP}"
    - name: run test with ${{ matrix.xcode }}
      run: |
        echo "set: ${XCODE_VERSION}"
        DEVELOPER_DIR="/Applications/${XCODE_VERSION}/Contents/Developer" bundle exec fastlane test
