name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [ '11.2.1', '11.3.1', 'latest' ]
        os: [ macos-10.15 ]
    steps:
    - uses: actions/checkout@v2
    - name: Cache bundle directory
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: set Xcode Version ${{ matrix.xcode }}
      run: |
        if [ "${{ matrix.xcode }}" = 'latest' ]; then
          export XCODE_APP=`ls /Applications/ | grep Xcode_ | sort -n | tail -1`
        else
          export XCODE_APP="Xcode_${{ matrix.xcode }}.app"
        fi
        echo "::set-env name=XCODE_VERSION::${XCODE_APP}"
    - name: run test with "${XCODE_VERSION}"
      run: DEVELOPER_DIR="/Applications/${XCODE_VERSION}/Contents/Developer" bundle exec fastlane test
